### ISSUE TITLE
babel-plugin-add-module-exports

### ISSUE THREAD

**Issue by codeuniquely** [jherax/array-sort-by#5]
When using webpack + babel to build my simple app this error message is shown on compile...

```
ERROR in ./node_modules/array-sort-by/src/sort-by.js
Module build failed: ReferenceError: Unknown plugin "babel-plugin-add-module-exports" specified 
  in "/project/node_modules/array-sort-by/package.json" 
  at 0, attempted to resolve relative to "/project/node_modules/array-sort-by"
    at /project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/project/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/project/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/project/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/project/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/project/node_modules/babel-loader/lib/index.js:175:20)
 @ ./src/App.js
 @ ./src/index.js
 @ multi babel-polyfill ./src/index.js
```

Should the *'array-sort-by'* package.json be including the babel plugin ???

**Comment by jherax** [comment]
Hi Steve, when including source code from a library you should add the
dependencies from that package, in this case you should add the package "
babel-plugin-add-module-exports" to your package.json.

**Comment by codeuniquely** [comment]
cheers
